server:
    port: 8000

spring:
  application:
    name: event-service
  profiles:
    active: default
  config:
    import: ${SPRING_CONFIG_IMPORT:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}


springdoc:
  api-docs:
    path: /events/v3/api-docs
  swagger-ui:
    url: /events/v3/api-docs
  override-server-url: true