spring:
  application:
    name: payment-service
  profiles:
    active: default
  config:
    import: "configserver:http://localhost:8888"

server:
  port: 8200

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /payments/v3/api-docs
  swagger-ui:
    url: /payments/v3/api-docs
  override-server-url: true