server:
  port: 8100

spring:
  application:
    name: registration-service
  profiles:
    active: default
  config:
    import: "configserver:http://localhost:8888"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      registrationCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    instances:
      registrationRetry:
        maxAttempts: 3
        waitDuration: 2s
  ratelimiter:
    instances:
      registrationRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s

springdoc:
  api-docs:
    path: /registrations/v3/api-docs
  swagger-ui:
    url: /registrations/v3/api-docs
  override-server-url: true