server:
  port: 8100

spring:
  application:
    name: registration-service
  profiles:
    active: default
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://config-server:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka}

resilience4j:
  circuitbreaker:
    instances:
      registrationService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 2
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
  retry:
    instances:
      registrationRetry:
        maxAttempts: 3
        waitDuration: 3s
      paymentRetry:
        maxAttempts: 2
        waitDuration: 1s
  ratelimiter:
    instances:
      registrationRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s

springdoc:
  api-docs:
    path: /registrations/v3/api-docs