spring:
  application:
    name: payment-service
  profiles:
    active: default
  config:
    import: {SPRING_CONFIG_IMPORT:configserver:http://config-server:8888}

server:
  port: 8200

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka}

springdoc:
  api-docs:
    path: /payments/v3/api-docs