server:
  port: 8000

spring:
  application:
    name: event-service
  profiles:
    active: default
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://config-server:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka}

springdoc:
  api-docs:
    path: /events/v3/api-docs